spring.application.name=rise

# DataBase
spring.profiles.active=env
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.security.user.password=1234

# Spring Security Oauth API's
spring.security.oauth2.client.registration.google.client-id=${OAUTH_NAME}
spring.security.oauth2.client.registration.google.client-secret=${OAUTH_Secret}


# AI API's

